[build]
  command = "npm run build"
  publish = "dist"
  base = "frontend"

[build.environment]
  VITE_API_BASE = "https://global-port-pass-api.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
