version: '3.9'
services:
  api:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - .env.example
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gpp_user
      POSTGRES_PASSWORD: gpp_pass
      POSTGRES_DB: gpp_db
    ports:
      - '5432:5432'
  minio:
    image: minio/minio
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
